menu:
    Home: /
    Archive: /archives/
    About: /about/
    # GitHub: https://github.com/xwartz
    # Rss: /atom.xml

favicon: /logo.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: pupa
duoshuo:

# Analytics
# google-analytics:
ga: UA-69822347-1
# baidu-analytics:
# ba: //hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2

# Copyright Infomation
startyear: 2015
